# Site
name: "LeestMeer"
title: "LeestMeer"
description: "Leesmateriaal voor SGBonaire. Nieuws, actualiteiten en boeken."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 
google_analytics: 
disqus: 
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Telegraaf:
    name: Telegraaf
    display_name: Telegraaf
    avatar: 'assets/images/telegraaf.png'
    email: 
    web: https://www.telegraaf.nl
    twitter: https://twitter.com/telegraaf
    description: "De Telegraaf is een landelijke Nederlandse ochtendkrant. Artikelen zijn terug te vinden op Telegraaf.nl"
  NOS:
    name: NOS
    display_name: NOS    
    avatar: 'assets/images/nos.png'
    email: 
    web: https://www.nos.nl
    twitter: https://twitter.com/nos
    description: "De NOS is de Nederlandse Omroep Stichting. Artikelen zijn terug te vinden op NOS.nl"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/:name/'
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    
# Pagination 
paginate: 24
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
